# Generated by Django 5.1.7 on 2025-05-29 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='submitter_has_reviewed_comments',
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
