# Generated by Django 5.2.1 on 2025-06-01 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_assignmentsubmission_is_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmissioncomment',
            name='line_number',
        ),
        migrations.AddField(
            model_name='assignmentsubmissioncomment',
            name='end_line',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentsubmissioncomment',
            name='end_offset',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentsubmissioncomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.assignmentsubmissioncomment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmissioncomment',
            name='start_line',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentsubmissioncomment',
            name='start_offset',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
