# Generated by Django 5.2.1 on 2025-06-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_assignmentsubmissioncomment_line_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_current',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submitter_has_reviewed_comments',
            field=models.BooleanField(default=False),
        ),
    ]
